"""
E3 persona-coordinate displacement re-encode driver — the GPU driver.

Spec: docs/research/portfolio.md §E3 (binding) + docs/prereg/E3.md. Effect-side
keystone: WHICH persona coordinates move under emotion steering, and is the
movement SELF/OTHER frame-dependent? Diagnostic, not causal — it aims E5.

Data reuse is mandatory: no new emotion-steered generation, no new judging. The
driver re-encodes the EXISTING scored free-form generations
(``suite/<key>/analysis/qualia_freeform_scored.json``; records carry
condition/strength/frame/text) with teacher-forced forward passes, captures the
residual stream at layers {32, 42, 50} simultaneously (in-driver multi-layer hook
helper — :class:`ProbedModel` stays untouched), mean-pools over the response-token
span (from the recorded ``prompt_tokens``), and stores raw projections onto the
frozen E1 coordinates. Token-resolved projections at first-person-pronoun /
experience-claim positions are recorded as the washout guard. Nothing is
aggregated on GPU; all confirmatory inference (T1-T6, exact 252-enumeration via
``scripts/exact_perm.py``) is CPU-side and lives in a separate stats script.

Arms (portfolio §E3 fix arms; the 2×2 re-encode is arms 1-4):

* ``reencode_unsteered``       — each record's own text, unsteered forward
                                 (text-driven component; includes the per-frame
                                 strength-0 baselines).
* ``reencode_steered``         — own text with the record's (condition, strength)
                                 steer context active during the forward pass
                                 (state + text).
* ``reencode_unsteered_swap``  — text swapped across SELF/OTHER contexts,
                                 unsteered (text-driven displacement follows the
                                 text).
* ``reencode_steered_swap``    — swapped text, steer context active (state-driven
                                 displacement follows the steer context).
* ``direct_add``               — analytic null: unsteered prompt-only forward,
                                 then α·v_e added NUMERICALLY at layers ≥ the
                                 injection layer (α = strength × calibration
                                 norm) — the pure linear-propagation prediction
                                 to subtract. Includes the strength-0 prompt
                                 cells as the base points.
* ``prompt_steered``           — prompt-only forward under the steer context
                                 (actual propagation without generation).
* ``persona_control``          — positive control: system-prompt role inductions
                                 (empath / poet / accountant), n generations per
                                 role × frame through the identical capture
                                 pipeline — sets the axis-displacement scale for
                                 a "detectable persona shift".

Projections per (record, arm, layer): assistant axis a[L], human axis h[L],
h_purged[L], experiencer axis z_x[L] (prereg E3: unit(mean frozen
experiencer_high roles − frozen experiencer_low roles), orthogonalized against
a — built here from the frozen role subsets + atlas, never re-derived),
valence axis[L], PC1-8 role-space coordinates, plus the injected
emotion's own direction two ways — ``v_injected`` (the emotion's layer-local
direction v_e[L]) and ``v_injected_steer`` (the vector actually added at the
injection layer, the one linear propagation carries to L50; this is what the
injection-artifact residualization needs). The per-layer coordinate Gram matrix
and the cos(v_e, coordinate) table are published in the provenance header
(prereg: "publish the cos table up front"; collinearity gate reads the Gram).

Strengths: confirmatory {0, 0.06, 0.10}; s=0.15 records are kept but flagged
``descriptive_only`` (self_attribution saturates the scale there — portfolio
REJECTED list); other shipped strengths (0.03) are dropped. The
``__random__``/``__mean_all__`` top-up mandated by §E3 is generated by re-running
the *freeform* driver (that is where generation lives) and feeding the scored
result here via ``--extra-scored``.

INTEGRATION (E1 workstream, ``emotion_probes.persona.geometry`` — not owned by
this file; :func:`frozen_directions` is the single adapter point, verified
against the landed API):

    geometry.build_directions(bank, ax, subsets, layer, seed=0)
        -> {"a", "h", "h_purged", "valence", "v_<emotion>": unit (5120,)}
    geometry.pca_atlas(ax, layer, center="default", n_pcs=8)
        -> {..., "components": (n_pcs, 5120)}

If geometry's API moves, only :func:`frozen_directions` changes; alternatively
E1 can export the frozen coordinates to an ``.npz`` (keys ``"<name>@L<layer>"``)
consumed via ``--directions``. Tests inject directions straight into
:meth:`PersonaDisplacementExperiment.run`.

Requirements: a real chat model on a GPU (torch imported lazily; the module
imports and unit-tests on a laptop).

    python -m emotion_probes.alignment.persona_displacement --suite qwen3-32b \
        --layers 32 42 50
    python -m emotion_probes.alignment.persona_displacement --quick   # smoke
"""

from __future__ import annotations

import argparse
import json
import os
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator, Sequence

import numpy as np

from emotion_probes.config import Config
from emotion_probes.core.probes import ProbeBank
from emotion_probes.models.language_model import ProbedModel
from emotion_probes.alignment.qualia_steering import QualiaSteeringExperiment
from emotion_probes.data import qualia

# Pre-registered layer set (prereg E3: L50 primary, L32 text-mediated-only
# comparator, L42 descriptive) — the steering layer stays the ~2/3-depth layer.
DEFAULT_CAPTURE_LAYERS = [32, 42, 50]
LAYER_ROLES = {32: "text_mediated_comparator", 42: "descriptive", 50: "primary"}

CONFIRMATORY_STRENGTHS = (0.0, 0.06, 0.10)
DESCRIPTIVE_STRENGTHS = (0.15,)          # kept if present, flagged descriptive_only
BASELINE = "__baseline__"

ARM_REENC_UNSTEERED = "reencode_unsteered"
ARM_REENC_STEERED = "reencode_steered"
ARM_REENC_UNSTEERED_SWAP = "reencode_unsteered_swap"
ARM_REENC_STEERED_SWAP = "reencode_steered_swap"
ARM_DIRECT_ADD = "direct_add"
ARM_PROMPT_STEERED = "prompt_steered"
ARM_PERSONA_CONTROL = "persona_control"
ALL_ARMS = [
    ARM_REENC_UNSTEERED, ARM_REENC_STEERED,
    ARM_REENC_UNSTEERED_SWAP, ARM_REENC_STEERED_SWAP,
    ARM_DIRECT_ADD, ARM_PROMPT_STEERED, ARM_PERSONA_CONTROL,
]

# The SELF/OTHER text-swap pair (SCENE is the expressibility floor, never swapped).
SWAP_FRAMES = {"self": "other", "other": "self"}

# Positive-control roles (portfolio §E3: "you are an empath / poet / accountant").
CONTROL_ROLES = ["empath", "poet", "accountant"]
DEFAULT_CONTROL_N = 10
DEFAULT_MAX_NEW_TOKENS = 180
DEFAULT_TEMPERATURE = 0.9
DEFAULT_GEN_BATCH = 8

_REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_ROLE_ROOT = (_REPO_ROOT / "persona_assets" / "assistant-axis-repo-data"
                     / "roles" / "instructions")

# The confirmatory coordinate family (prereg E3: z_a and z_x are load-bearing —
# T1/T3/T4/T6 are all built on the experiencer-axis projection). run() refuses
# direction sets missing any of these, so a GPU run can never silently produce
# projections the confirmatory family cannot be computed from.
REQUIRED_DIRECTIONS = ("assistant_axis", "human_axis", "human_axis_purged",
                       "experiencer_axis", "valence_axis")
DIRECTION_NAMES = list(REQUIRED_DIRECTIONS) + [f"pc{i}" for i in range(1, 9)]

# Washout guard: first-person-pronoun + experience-claim token surface forms
# (prereg E3 "token-resolved projections at first-person-pronoun/experience-claim
# positions"). Matched against each decoded response token, stripped + lowercased.
FIRST_PERSON_TOKENS = {"i", "i'm", "im", "i've", "ive", "i'd", "i'll",
                       "me", "my", "mine", "myself"}
EXPERIENCE_TOKENS = {"feel", "feels", "feeling", "feelings", "felt",
                     "experience", "experiencing", "experienced",
                     "conscious", "consciousness", "aware", "awareness",
                     "sense", "sensing", "sensation", "sensations"}
WASHOUT_TOKENS = FIRST_PERSON_TOKENS | EXPERIENCE_TOKENS

# --quick smoke subset.
QUICK_EMOTIONS = ["blissful", "terrified", qualia.RANDOM_DIRECTION]
QUICK_RECORDS_PER_CELL = 2
QUICK_CONTROL_N = 2


def _snap(s) -> float:
    """Snap a strength for use as a grouping key (compute_qualia_stats convention)."""
    return round(float(s), 6)


def _unit(v: np.ndarray) -> np.ndarray:
    v = np.asarray(v, dtype=np.float32)
    n = float(np.linalg.norm(v))
    if n == 0.0 or not np.isfinite(n):
        raise ValueError(f"cannot unit-normalize direction with norm {n}")
    return v / n


# --------------------------------------------------------------------------- #
# Multi-layer capture — in-driver helper modeled on ProbedModel._capture
# (language_model.py is owned by another workstream and must not be edited).
# --------------------------------------------------------------------------- #
@contextmanager
def multi_layer_capture(model: ProbedModel, layers: Sequence[int]) -> Iterator[dict]:
    """Forward hooks on several decoder layers at once; yields ``{layer: tensor}``
    repopulated on every forward pass while open (each tensor ``(B, T, H)``,
    detached). Same mechanism as :meth:`ProbedModel._capture`, but private to
    this driver so E3 never depends on wrapper internals beyond ``_layers``."""
    captured: dict[int, object] = {}
    handles = []

    def make_hook(idx: int):
        def hook(_module, _inp, output):
            captured[idx] = (output[0] if isinstance(output, tuple) else output).detach()
        return hook

    for idx in layers:
        handles.append(model._layers[idx].register_forward_hook(make_hook(idx)))
    try:
        yield captured
    finally:
        for h in handles:
            h.remove()


# --------------------------------------------------------------------------- #
# Source records (the existing scored free-form generations)
# --------------------------------------------------------------------------- #
def load_scored(paths: Sequence[tuple[str, Path]]) -> tuple[list[dict], dict, list[dict]]:
    """Load one or more ``qualia_freeform_scored.json`` payloads.

    Returns ``(records, frames_meta, source_meta)``. Each record keeps only the
    fields E3 needs plus a stable ``record_id`` = ``"<tag>#<index>"`` (index into
    that file's ``records`` list — downstream stats join judge scores back through
    it). ``frames_meta`` maps frame key -> the frame dict (first file wins);
    ``rendered``/``prompt_tokens`` may be absent in old payloads (caller fills).
    ``source_meta`` carries each source run's provenance (seed, calibration norm,
    steer layer, model id) — run() uses it to guard the ``__random__``
    reconstruction and the α-scaling consistency."""
    records: list[dict] = []
    frames_meta: dict[str, dict] = {}
    source_meta: list[dict] = []
    for tag, p in paths:
        payload = json.loads(Path(p).read_text())
        source_meta.append({
            "tag": tag, "path": str(p),
            "seed": payload.get("seed"),
            "calibration_norm": payload.get("calibration_norm"),
            "steer_layer": payload.get("layer"),
            "model_id": payload.get("model_id"),
        })
        for f in payload.get("frames", []):
            frames_meta.setdefault(f["key"], dict(f))
        for i, r in enumerate(payload.get("records", [])):
            records.append({
                "record_id": f"{tag}#{i}",
                "condition": r["condition"],
                "strength": _snap(r.get("strength", 0.0)),
                "frame": r["frame"],
                "sample": r.get("sample"),
                "text": r.get("text", ""),
            })
    return records, frames_meta, source_meta


def select_records(records: Sequence[dict], confirmatory: Sequence[float],
                   descriptive: Sequence[float] = DESCRIPTIVE_STRENGTHS,
                   emotions: Sequence[str] | None = None,
                   max_per_cell: int | None = None) -> list[dict]:
    """Filter to the pre-registered strengths and (optionally) a condition subset.

    A record is kept iff its snapped strength is confirmatory or descriptive;
    descriptive records gain ``descriptive_only=True``. ``__baseline__`` records
    are always kept, regardless of the strength filter (per-frame strength-0
    baselines are load-bearing — prereg E3). With ``max_per_cell``, keeps the
    first k records per (condition, strength, frame) cell (the --quick path)."""
    conf = {_snap(s) for s in confirmatory}
    desc = {_snap(s) for s in descriptive} - conf
    keep_names = set(emotions) if emotions is not None else None
    out: list[dict] = []
    cell_counts: dict[tuple, int] = {}
    for r in records:
        s = _snap(r["strength"])
        if r["condition"] != BASELINE and s not in conf and s not in desc:
            continue
        if keep_names is not None and r["condition"] != BASELINE \
                and r["condition"] not in keep_names:
            continue
        cell = (r["condition"], s, r["frame"])
        cell_counts[cell] = cell_counts.get(cell, 0) + 1
        if max_per_cell is not None and cell_counts[cell] > max_per_cell:
            continue
        out.append({**r, "strength": s, "descriptive_only": s in desc})
    return out


# --------------------------------------------------------------------------- #
# Frozen E1 coordinates
# --------------------------------------------------------------------------- #
def experiencer_axis(ax, subsets: dict, layer: int) -> np.ndarray:
    """z_x at one layer, exactly as pre-registered (prereg E3 "Coordinates"):
    unit(mean frozen experiencer roles − matched non-experiencer roles) from the
    275-role atlas, **orthogonalized against a**. The role sets are the FROZEN
    adjudicated ``experiencer_high``/``experiencer_low`` subsets
    (docs/prereg/role_subsets.json) — never re-derived from ratings here."""
    sub = subsets.get("subsets", subsets)
    try:
        high, low = list(sub["experiencer_high"]), list(sub["experiencer_low"])
    except (KeyError, TypeError) as exc:
        keys = sorted(sub) if isinstance(sub, dict) else type(sub).__name__
        raise KeyError(
            "role_subsets has no frozen 'experiencer_high'/'experiencer_low' sets "
            f"(found: {keys}) — E3's z_x coordinate requires the frozen "
            "experiencer role sets (portfolio Day-0 item 4)") from exc
    missing = [n for n in [*high, *low] if n not in ax.role_vectors]
    if missing:
        raise KeyError(f"experiencer roles missing from the role atlas: {missing}")
    x = (np.mean([ax.role_vectors[n][layer] for n in high], axis=0)
         - np.mean([ax.role_vectors[n][layer] for n in low], axis=0)).astype(np.float32)
    a = ax.unit_axis(layer)
    x = x - float(x @ a) * a                    # prereg: orthogonalized against a
    return _unit(x)


def frozen_directions(layers: Sequence[int], k_pcs: int = 8, seed: int = 0) -> dict[int, dict]:
    """Build ``{layer: {name: unit vector}}`` from the frozen persona assets +
    E1 geometry (see INTEGRATION in the module docstring). This is the ONLY
    place that touches ``emotion_probes.persona.geometry``."""
    from emotion_probes.persona import assets
    from emotion_probes.persona import geometry  # E1 workstream

    ax = assets.load_assistant_axis()
    assets.anchor_check(ax)                       # sign/index convention guard
    subsets = assets.load_role_subsets()
    ebank = assets.load_emotion_bank()
    out: dict[int, dict] = {}
    for layer in layers:
        g = geometry.build_directions(ebank, ax, subsets, int(layer), seed=seed)
        d = {
            "assistant_axis": _unit(g["a"]),
            "human_axis": _unit(g["h"]),
            "human_axis_purged": _unit(g["h_purged"]),
            "experiencer_axis": experiencer_axis(ax, subsets, int(layer)),
            "valence_axis": _unit(g["valence"]),
        }
        atlas = geometry.pca_atlas(ax, int(layer), center="default", n_pcs=k_pcs)
        for i in range(int(atlas["n_pcs"])):
            d[f"pc{i + 1}"] = _unit(np.asarray(atlas["components"])[i])
        out[int(layer)] = d
    return out


def load_directions_npz(path: str | Path, layers: Sequence[int]) -> dict[int, dict]:
    """Load pre-exported frozen directions from an ``.npz`` with keys
    ``"<name>@L<layer>"`` (the E1 export fallback)."""
    z = np.load(Path(path))
    out: dict[int, dict] = {}
    for layer in layers:
        d = {}
        for key in z.files:
            if key.endswith(f"@L{int(layer)}"):
                d[key.rsplit("@L", 1)[0]] = _unit(z[key])
        if not d:
            raise KeyError(f"{path}: no '<name>@L{int(layer)}' keys for layer {layer}")
        out[int(layer)] = d
    return out


def load_role_instruction(role: str, root: str | Path | None = None) -> str:
    """First 'pos' system-prompt variant for a role from the assistant-axis repo
    data (``roles/instructions/<role>.json``)."""
    root = Path(root) if root is not None else DEFAULT_ROLE_ROOT
    with open(root / f"{role}.json") as fh:
        spec = json.load(fh)
    return spec["instruction"][0]["pos"]


# --------------------------------------------------------------------------- #
# The experiment
# --------------------------------------------------------------------------- #
class PersonaDisplacementExperiment(QualiaSteeringExperiment):
    """Forward-only persona-coordinate displacement decomposition (E3).

    Inherits the single ~2/3-depth steering layer, ``_synthetic_vectors`` and the
    ``_steer`` routing (real emotions -> engine, synthetic -> ``model.steer`` at
    the matched calibrated norm) from the logit driver; adds simultaneous
    multi-layer capture, teacher-forced re-encoding, the analytic direct-add
    null, and the system-prompt persona positive control.
    """

    def __init__(self, model: ProbedModel, bank: ProbeBank, config: Config | None = None,
                 capture_layers: Sequence[int] = DEFAULT_CAPTURE_LAYERS):
        super().__init__(model, bank, config)     # sets self.layer (steering layer)
        self.capture_layers = sorted(int(l) for l in capture_layers)

    # ------------------------------------------------------------------ #
    # Rendering + forwards
    # ------------------------------------------------------------------ #
    def _render_conv(self, msgs: list[dict]) -> str:
        """Render a message list through the chat template (no YES/NO suffix)."""
        kwargs = {}
        if self.config.enable_thinking is not None:
            kwargs["enable_thinking"] = self.config.enable_thinking
        return self.model.tokenizer.apply_chat_template(
            msgs, tokenize=False, add_generation_prompt=True, **kwargs
        )

    def _forward_tokens(self, token_ids: Sequence[int]) -> dict[int, np.ndarray]:
        """One teacher-forced forward pass; residual stream at every capture
        layer, ``{layer: (T, H) float32}``."""
        import torch

        input_ids = torch.tensor([list(token_ids)], device=self.model._input_device)
        with multi_layer_capture(self.model, self.capture_layers) as cap:
            with torch.no_grad():
                self.model.model(input_ids=input_ids)
        return {L: cap[L].to(torch.float32).cpu().numpy()[0] for L in self.capture_layers}

    def _reencode(self, rendered_prompt: str, response: str,
                  n_prompt: int | None = None, max_length: int | None = None) -> dict:
        """Teacher-force ``[prompt + response]``, mean-pool the response span.

        The span starts at ``n_prompt`` (the RECORDED ``prompt_tokens`` when
        available — prereg E3 — else the tokenized prompt length), clamped so at
        least one token is pooled (same convention as
        :meth:`ProbedModel.mean_residual_over_span`). Also pools the washout-
        guard positions (first-person-pronoun / experience-claim tokens)."""
        tok = self.model.tokenizer
        max_length = max_length or getattr(self.config, "deflection_max_length", None) or 4096
        full_ids = tok(rendered_prompt + response, add_special_tokens=False)["input_ids"]
        full_ids = full_ids[:max_length]
        if n_prompt is None:
            n_prompt = len(tok(rendered_prompt, add_special_tokens=False)["input_ids"])
        n_prompt = min(int(n_prompt), max(0, len(full_ids) - 1))

        acts = self._forward_tokens(full_ids)
        resp_ids = full_ids[n_prompt:]
        washout_idx = [i for i, tid in enumerate(resp_ids)
                       if tok.decode([tid]).strip().lower() in WASHOUT_TOKENS]

        pooled, washout_pooled = {}, {}
        for L, a in acts.items():
            span = a[n_prompt:]
            if span.shape[0] == 0:
                span = a[-1:]
            pooled[L] = span.mean(axis=0)
            washout_pooled[L] = (span[washout_idx].mean(axis=0) if washout_idx else None)
        return {"pooled": pooled, "washout_pooled": washout_pooled,
                "washout_tokens": len(washout_idx), "response_tokens": len(resp_ids)}

    def _prompt_acts(self, rendered_prompt: str) -> dict[int, np.ndarray]:
        """Residual stream at the FINAL prompt position (the pre-response
        position where generation would begin), ``{layer: (H,)}``."""
        ids = self.model.tokenizer(rendered_prompt, add_special_tokens=False)["input_ids"]
        acts = self._forward_tokens(ids)
        return {L: a[-1] for L, a in acts.items()}

    def _gen_samples(self, rendered_prompt: str, n: int, max_new_tokens: int,
                     temperature: float, gen_batch: int) -> list[str]:
        """n sampled continuations for one rendered prompt (chunked batched gen)."""
        outs: list[str] = []
        for start in range(0, n, gen_batch):
            k = min(gen_batch, n - start)
            outs.extend(self.model.generate_batch(
                [rendered_prompt] * k, max_new_tokens=max_new_tokens,
                temperature=temperature, do_sample=True, chat=False,
            ))
        return outs

    # ------------------------------------------------------------------ #
    # Projections
    # ------------------------------------------------------------------ #
    @staticmethod
    def _project(vec: np.ndarray, dirs: dict, v_e_layer: np.ndarray | None,
                 v_e_steer: np.ndarray | None) -> dict:
        """Raw (uncentered) scalar projections of one pooled activation onto the
        frozen unit coordinates + the injected direction (layer-local and
        as-injected). Uncentered by design: every statistic downstream is a
        within-frame difference against the strength-0 baselines, which cancels
        any constant offset exactly."""
        vec = np.asarray(vec, dtype=np.float32)
        out = {name: round(float(vec @ d), 5) for name, d in dirs.items()}
        out["v_injected"] = (round(float(vec @ v_e_layer), 5)
                             if v_e_layer is not None else None)
        out["v_injected_steer"] = (round(float(vec @ v_e_steer), 5)
                                   if v_e_steer is not None else None)
        return out

    def _emit(self, rows: list[dict], base: dict, dirs: dict,
              pooled: dict[int, np.ndarray], v_e_layer: dict | None,
              v_e_steer: np.ndarray | None, washout_pooled: dict | None = None,
              washout_tokens: int | None = None) -> None:
        """Append one flat output record per capture layer."""
        for L in self.capture_layers:
            row = dict(base)
            row["layer"] = int(L)
            row["projections"] = self._project(
                pooled[L], dirs[L],
                v_e_layer.get(L) if v_e_layer is not None else None, v_e_steer)
            if washout_pooled is not None:
                w = washout_pooled.get(L)
                row["projections_washout"] = (
                    self._project(w, dirs[L],
                                  v_e_layer.get(L) if v_e_layer is not None else None,
                                  v_e_steer)
                    if w is not None else None)
                row["washout_tokens"] = int(washout_tokens or 0)
            rows.append(row)

    # ------------------------------------------------------------------ #
    # The sweep
    # ------------------------------------------------------------------ #
    def run(self, scored_path: str | Path | None = None,
            extra_scored: Sequence[str | Path] = (),
            arms: Sequence[str] | None = None,
            emotions: Sequence[str] | None = None,
            strengths: Sequence[float] | None = None,
            directions: dict[int, dict] | None = None,
            n_control: int = DEFAULT_CONTROL_N,
            control_roles: Sequence[str] = CONTROL_ROLES,
            role_root: str | Path | None = None,
            max_records_per_cell: int | None = None,
            max_new_tokens: int = DEFAULT_MAX_NEW_TOKENS,
            temperature: float = DEFAULT_TEMPERATURE,
            gen_batch: int = DEFAULT_GEN_BATCH, seed: int = 0) -> dict:
        """Re-encode the scored generations through every requested arm.

        Forward-only except ``persona_control`` (the one arm that generates).
        One steer context per (condition, strength) cell; unknown conditions
        (e.g. extra random draws whose seeds this driver cannot reconstruct) are
        excluded from steered/analytic arms and listed in the header."""
        import torch

        np.random.seed(seed)
        torch.manual_seed(seed)

        arms = list(arms) if arms is not None else list(ALL_ARMS)
        bad = [a for a in arms if a not in ALL_ARMS]
        if bad:
            raise ValueError(f"unknown arms {bad}; valid: {ALL_ARMS}")

        # ---- sources ----
        scored_path = (Path(scored_path) if scored_path is not None
                       else self.config.analysis_dir / "qualia_freeform_scored.json")
        sources = [("main", Path(scored_path))]
        sources += [(f"extra{i}", Path(p)) for i, p in enumerate(extra_scored)]
        all_records, frames_meta, source_meta = load_scored(sources)
        confirmatory = list(strengths) if strengths is not None else list(CONFIRMATORY_STRENGTHS)
        kept = select_records(all_records, confirmatory, DESCRIPTIVE_STRENGTHS,
                              emotions=emotions, max_per_cell=max_records_per_cell)
        kept = [r for r in kept if r["frame"] in frames_meta]

        # frames: rendered prompt + recorded prompt_tokens (fallback: re-render)
        for key, f in frames_meta.items():
            if not f.get("rendered"):
                f["rendered"] = self._render_conv([{"role": "user", "content": f["text"]}])
            if not f.get("prompt_tokens"):
                f["prompt_tokens"] = len(self.model.tokenizer(
                    f["rendered"], add_special_tokens=False)["input_ids"])

        # ---- calibration (skip=0 inside; the frames' own rendered prompts) ----
        self.calibrate([f["rendered"] for f in frames_meta.values()])
        calib_norm = float(self.engine._require_norms().get(self.layer, 0.0))
        # α = strength × calibration_norm must be the SAME scaling the source
        # run's generation-time steering used; cross-check against its header.
        main_meta = source_meta[0]
        src_calib = main_meta.get("calibration_norm")
        if (src_calib and main_meta.get("steer_layer") == self.layer
                and abs(calib_norm - float(src_calib)) > 0.01 * abs(float(src_calib))):
            import warnings
            warnings.warn(
                f"re-derived calibration norm {calib_norm:.3f} differs from the source "
                f"run's {float(src_calib):.3f} by >1% at layer {self.layer} — direct-add "
                "α and the steered re-encode would not match the generation-time "
                "scaling (wrong model/frames pairing?)", stacklevel=2)

        # ---- frozen coordinates ----
        dirs = directions if directions is not None else frozen_directions(self.capture_layers)
        dirs = {int(L): {n: _unit(v) for n, v in d.items()} for L, d in dirs.items()}
        missing = [L for L in self.capture_layers if L not in dirs]
        if missing:
            raise KeyError(f"directions missing capture layers {missing}")
        bad_names = {L: [n for n in REQUIRED_DIRECTIONS if n not in dirs[L]]
                     for L in self.capture_layers}
        bad_names = {L: m for L, m in bad_names.items() if m}
        if bad_names:
            raise KeyError("directions missing required confirmatory coordinates "
                           f"(prereg E3 z_a/z_x family): {bad_names}")

        # ---- injected directions per condition ----
        synth = self._synthetic_vectors(seed=seed)
        # __random__ is reproducible ONLY under the seed the source run used; a
        # mismatched seed would silently steer a DIFFERENT random vector while
        # still labeling rows "__random__" (a mislabeled control band).
        # __mean_all__ is seed-independent and is unaffected.
        src_seeds = {int(m["seed"]) for m in source_meta if m.get("seed") is not None}
        random_seed_ok = (not src_seeds) or src_seeds == {int(seed)}
        conditions = sorted({r["condition"] for r in kept})
        v_layer: dict[str, dict[int, np.ndarray]] = {}   # emotion's own dir at each layer
        v_steer: dict[str, np.ndarray] = {}              # the vector actually injected
        skipped: list[str] = []
        for c in conditions:
            if c == BASELINE:
                continue
            if c == qualia.RANDOM_DIRECTION and not random_seed_ok:
                skipped.append(c)
                continue
            if c in synth:
                v_steer[c] = _unit(synth[c])
                if c == qualia.MEAN_ALL_DIRECTION:
                    v_layer[c] = {L: _unit(self.bank.vectors[L].mean(axis=0))
                                  for L in self.capture_layers}
                else:
                    v_layer[c] = {L: _unit(synth[c]) for L in self.capture_layers}
                continue
            try:
                idx = self.bank.index_of(c)
            except (KeyError, ValueError):
                skipped.append(c)
                continue
            v_steer[c] = _unit(self.bank.vectors[self.layer, idx])
            v_layer[c] = {L: _unit(self.bank.vectors[L, idx]) for L in self.capture_layers}

        # ---- provenance geometry: Gram matrix + cos(v_e, coordinate) table ----
        names = sorted(dirs[self.capture_layers[0]])
        gram = {str(L): {a: {b: round(float(dirs[L][a] @ dirs[L][b]), 5) for b in names}
                         for a in names} for L in self.capture_layers}
        cos_v_e = {c: {str(L): {n: round(float(v_layer[c][L] @ dirs[L][n]), 5)
                                for n in names}
                       for L in self.capture_layers} for c in sorted(v_layer)}

        rows: list[dict] = []

        def rec_base(r: dict, arm: str, encode_frame: str, span: str) -> dict:
            return {"record_id": r["record_id"], "arm": arm,
                    "condition": r["condition"], "strength": float(r["strength"]),
                    "frame": r["frame"], "encode_frame": encode_frame,
                    "sample": r.get("sample"), "span": span,
                    "descriptive_only": bool(r.get("descriptive_only", False))}

        # ---- arms 1 + 3: unsteered re-encode (own text / swapped context) ----
        for arm, swap in ((ARM_REENC_UNSTEERED, False), (ARM_REENC_UNSTEERED_SWAP, True)):
            if arm not in arms:
                continue
            for r in kept:
                ef = SWAP_FRAMES.get(r["frame"]) if swap else r["frame"]
                if ef is None or ef not in frames_meta:
                    continue
                f = frames_meta[ef]
                enc = self._reencode(f["rendered"], r["text"], n_prompt=f["prompt_tokens"])
                base = rec_base(r, arm, ef, "response")
                base["response_tokens"] = enc["response_tokens"]
                self._emit(rows, base, dirs, enc["pooled"], v_layer.get(r["condition"]),
                           v_steer.get(r["condition"]), enc["washout_pooled"],
                           enc["washout_tokens"])

        # ---- arms 2 + 4: steered re-encode (one steer context per cell) ----
        # Hook order is load-bearing: the steer context is entered BEFORE
        # _reencode registers the capture hooks, so at the steer layer the
        # capture sees the POST-injection residual (torch runs forward hooks in
        # registration order, threading each hook's returned output into the
        # next). This is exactly what the prereg's injection-artifact handling
        # assumes ("at layers >= 42 the captured state literally contains
        # α·v_emotion"). Do not reorder.
        steered_cells: dict[tuple, list[dict]] = {}
        for r in kept:
            if r["strength"] > 0 and r["condition"] in v_steer:
                steered_cells.setdefault((r["condition"], r["strength"]), []).append(r)
        for arm, swap in ((ARM_REENC_STEERED, False), (ARM_REENC_STEERED_SWAP, True)):
            if arm not in arms:
                continue
            for (cond, s), cell_records in sorted(steered_cells.items()):
                with self._steer(cond, float(s), synth):
                    for r in cell_records:
                        ef = SWAP_FRAMES.get(r["frame"]) if swap else r["frame"]
                        if ef is None or ef not in frames_meta:
                            continue
                        f = frames_meta[ef]
                        enc = self._reencode(f["rendered"], r["text"],
                                             n_prompt=f["prompt_tokens"])
                        base = rec_base(r, arm, ef, "response")
                        base["response_tokens"] = enc["response_tokens"]
                        self._emit(rows, base, dirs, enc["pooled"], v_layer.get(cond),
                                   v_steer.get(cond), enc["washout_pooled"],
                                   enc["washout_tokens"])

        # ---- arm 5: direct-add analytic null (prompt-only, numeric injection) ----
        if ARM_DIRECT_ADD in arms:
            prompt_acts = {fk: self._prompt_acts(frames_meta[fk]["rendered"])
                           for fk in sorted({r["frame"] for r in kept})}
            # strength-0 base points, one per frame
            for fk, acts in sorted(prompt_acts.items()):
                base = {"record_id": f"cell:{BASELINE}:0.0:{fk}", "arm": ARM_DIRECT_ADD,
                        "condition": BASELINE, "strength": 0.0, "frame": fk,
                        "encode_frame": fk, "sample": None, "span": "prompt_final",
                        "descriptive_only": False}
                self._emit(rows, base, dirs, acts, None, None)
            cells = sorted({(r["condition"], r["strength"], r["frame"]) for r in kept
                            if r["strength"] > 0 and r["condition"] in v_steer})
            for cond, s, fk in cells:
                alpha = float(s) * calib_norm
                add = alpha * v_steer[cond]
                pooled = {L: (prompt_acts[fk][L] + add if L >= self.layer
                              else prompt_acts[fk][L])
                          for L in self.capture_layers}
                base = {"record_id": f"cell:{cond}:{_snap(s)}:{fk}", "arm": ARM_DIRECT_ADD,
                        "condition": cond, "strength": float(s), "frame": fk,
                        "encode_frame": fk, "sample": None, "span": "prompt_final",
                        "descriptive_only": _snap(s) in {_snap(x) for x in DESCRIPTIVE_STRENGTHS}}
                self._emit(rows, base, dirs, pooled, v_layer.get(cond), v_steer.get(cond))

        # ---- arm 6: prompt-only steered forward (propagation, no generation) ----
        if ARM_PROMPT_STEERED in arms:
            frames_present = sorted({r["frame"] for r in kept})
            for (cond, s) in sorted(steered_cells):
                with self._steer(cond, float(s), synth):
                    for fk in frames_present:
                        acts = self._prompt_acts(frames_meta[fk]["rendered"])
                        base = {"record_id": f"cell:{cond}:{_snap(s)}:{fk}",
                                "arm": ARM_PROMPT_STEERED, "condition": cond,
                                "strength": float(s), "frame": fk, "encode_frame": fk,
                                "sample": None, "span": "prompt_final",
                                "descriptive_only": _snap(s) in {_snap(x) for x in DESCRIPTIVE_STRENGTHS}}
                        self._emit(rows, base, dirs, acts, v_layer.get(cond),
                                   v_steer.get(cond))

        # ---- arm 7: persona-induction positive control (generates!) ----
        role_prompts: dict[str, str] = {}
        if ARM_PERSONA_CONTROL in arms:
            for role in control_roles:
                sys_prompt = load_role_instruction(role, role_root)
                role_prompts[role] = sys_prompt
                for fk, f in sorted(frames_meta.items()):
                    rendered = self._render_conv([
                        {"role": "system", "content": sys_prompt},
                        {"role": "user", "content": f["text"]},
                    ])
                    texts = self._gen_samples(rendered, n_control, max_new_tokens,
                                              temperature, gen_batch)
                    for i, text in enumerate(texts):
                        enc = self._reencode(rendered, text)   # unsteered, own tokenization
                        base = {"record_id": f"role:{role}:{fk}:{i}",
                                "arm": ARM_PERSONA_CONTROL, "condition": f"role:{role}",
                                "strength": 0.0, "frame": fk, "encode_frame": fk,
                                "sample": i, "span": "response",
                                "descriptive_only": False,
                                "response_tokens": enc["response_tokens"]}
                        self._emit(rows, base, dirs, enc["pooled"], None, None,
                                   enc["washout_pooled"], enc["washout_tokens"])

        # ---- payload ----
        cond_meta = []
        for c in conditions:
            spec = qualia.spec_for(c)
            cond_meta.append({"name": c, "steerable": c in v_steer,
                              "valence": spec.valence if spec else None,
                              "group": spec.group if spec else None})
        return {
            "model_id": self.config.model_id,
            "suite_key": os.environ.get("SUITE_KEY"),
            "experiment": "persona_displacement",
            "steer_layer": self.layer,
            "capture_layers": [int(L) for L in self.capture_layers],
            "layer_roles": {str(L): LAYER_ROLES.get(L, "exploratory")
                            for L in self.capture_layers},
            "num_layers": self.model.num_layers,
            "enable_thinking": self.config.enable_thinking,
            "calibration_norm": calib_norm,
            "strengths_confirmatory": sorted(_snap(s) for s in confirmatory),
            "strengths_descriptive": sorted(_snap(s) for s in DESCRIPTIVE_STRENGTHS),
            "arms": arms,
            "seed": int(seed),
            "n_control": int(n_control),
            "control_roles": role_prompts,
            "sources": source_meta,
            "n_source_records": len(all_records),
            "n_kept_records": len(kept),
            "frames": [{"key": k, **{kk: f.get(kk) for kk in
                                     ("label", "kind", "text", "rendered", "prompt_tokens")}}
                       for k, f in sorted(frames_meta.items())],
            "conditions": cond_meta,
            "skipped_conditions": sorted(skipped),
            "direction_names": names,
            "direction_gram": gram,
            "cos_v_e": cos_v_e,
            "records": rows,
        }


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def _apply_suite_env(key: str) -> None:
    """Pin Config's env vars from the suite manifest (same lines run_suite.sh evals)."""
    from emotion_probes.models import suite as suite_mod

    for line in suite_mod.env_exports(suite_mod.by_key(key)):
        k, v = line.removeprefix("export ").split("=", 1)
        os.environ[k] = v


def main() -> None:
    parser = argparse.ArgumentParser(
        description="E3 persona-coordinate displacement: re-encode the existing "
                    "scored free-form generations, capture layers {32,42,50}, and "
                    "project onto the frozen E1 persona coordinates."
    )
    parser.add_argument("--suite", default=None,
                        help="suite key (e.g. qwen3-32b) — exports the manifest env "
                             "before Config() when the runner has not already done so")
    parser.add_argument("--scored", default=None,
                        help="path to qualia_freeform_scored.json "
                             "(default: <analysis_dir>/qualia_freeform_scored.json)")
    parser.add_argument("--extra-scored", nargs="+", default=[],
                        help="additional scored files to merge (e.g. the "
                             "__random__/__mean_all__ top-up run)")
    parser.add_argument("--layers", nargs="+", type=int, default=DEFAULT_CAPTURE_LAYERS,
                        help=f"capture layers (default: {DEFAULT_CAPTURE_LAYERS})")
    parser.add_argument("--arms", nargs="+", default=None, choices=ALL_ARMS,
                        help="restrict to these arms (default: all)")
    parser.add_argument("--emotions", nargs="+", default=None,
                        help="restrict to these condition names (baselines always kept)")
    parser.add_argument("--strengths", nargs="+", type=float, default=None,
                        help=f"confirmatory strengths (default: {list(CONFIRMATORY_STRENGTHS)}; "
                             "s=0.15 records are always kept, flagged descriptive_only)")
    parser.add_argument("--directions", default=None,
                        help="npz of frozen directions (keys '<name>@L<layer>') — "
                             "fallback when persona.geometry is not importable")
    parser.add_argument("--n-control", type=int, default=DEFAULT_CONTROL_N,
                        help="generations per (role, frame) in the persona control")
    parser.add_argument("--max-new-tokens", type=int, default=DEFAULT_MAX_NEW_TOKENS)
    parser.add_argument("--temperature", type=float, default=DEFAULT_TEMPERATURE)
    parser.add_argument("--gen-batch", type=int, default=DEFAULT_GEN_BATCH)
    parser.add_argument("--quick", action="store_true",
                        help="smoke subset (few conditions, 2 records/cell, tiny control)")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--tag", default="",
                        help="suffix for the output filename (never clobbers the main run)")
    args = parser.parse_args()

    emotions, n_control, max_per_cell = args.emotions, args.n_control, None
    if args.quick:
        emotions = emotions or QUICK_EMOTIONS
        n_control = QUICK_CONTROL_N if args.n_control == DEFAULT_CONTROL_N else args.n_control
        max_per_cell = QUICK_RECORDS_PER_CELL

    if args.suite:
        _apply_suite_env(args.suite)
    config = Config()
    model = ProbedModel(config)
    bank = ProbeBank.load(config.emotion_vectors_path)
    bank.check_against(model, where="persona_displacement")
    experiment = PersonaDisplacementExperiment(model, bank, config,
                                               capture_layers=args.layers)
    directions = (load_directions_npz(args.directions, args.layers)
                  if args.directions else None)
    payload = experiment.run(
        scored_path=args.scored, extra_scored=args.extra_scored, arms=args.arms,
        emotions=emotions, strengths=args.strengths, directions=directions,
        n_control=n_control, max_records_per_cell=max_per_cell,
        max_new_tokens=args.max_new_tokens, temperature=args.temperature,
        gen_batch=args.gen_batch, seed=args.seed)
    path = experiment.save_json(f"persona_displacement{args.tag}.json", payload)

    print(f"wrote {path}")
    print(f"model={payload['model_id']}  suite={payload['suite_key']}  "
          f"steer_layer={payload['steer_layer']}  capture={payload['capture_layers']}  "
          f"calib_norm={payload['calibration_norm']:.2f}")
    by_arm: dict[str, int] = {}
    for r in payload["records"]:
        by_arm[r["arm"]] = by_arm.get(r["arm"], 0) + 1
    print(f"kept_source_records={payload['n_kept_records']}  "
          f"skipped_conditions={payload['skipped_conditions']}")
    for arm in payload["arms"]:
        print(f"  {arm:<26} {by_arm.get(arm, 0):>6} rows")
    # sanity: persona-control assistant-axis displacement vs unsteered baselines
    L = max(payload["capture_layers"])
    base_p = [r["projections"]["assistant_axis"] for r in payload["records"]
              if r["arm"] == ARM_REENC_UNSTEERED and r["condition"] == BASELINE
              and r["layer"] == L]
    ctrl_p = [r["projections"]["assistant_axis"] for r in payload["records"]
              if r["arm"] == ARM_PERSONA_CONTROL and r["layer"] == L]
    if base_p and ctrl_p:
        print(f"  persona-control assistant-axis displacement @L{L}: "
              f"{float(np.mean(ctrl_p) - np.mean(base_p)):+.3f} "
              "(negative = roles drift off-Assistant, as expected)")


if __name__ == "__main__":
    main()
